name: Build Windows
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.3.0
      
    - name: Install
      run: npm install
      
    - name: Build
      run: npm run electron:build --win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: word-eliminate-win.exe
        path: release/*.exe
        
