name: Build 
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.3.0
      
    - name: Install
      run: npm install
      
    - name: Build
      run: npm run electron:build --mac --${{ matrix.arch }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: word-eliminate-${{ matrix.arch }}
        path: release/*dmg